# # http://yuyin.baidu.com/
baidu_yuyin:
  api_key: 'qW5HLj4Ks6DfsCV2K9If5O80'
  secret_key: '37riCUCmGj1lfrhaGcyu11wWqCjvZbZR'
  app_id: '9217941'

homeassistant:
  url: 'http://localhost'
  port: '8123'
  password: 'raspberrypi'

tuling:
  key: 'be4efe7298b24d0d8c9b5542dd56671a'